config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.draw do
    root 'static_todos#home'
  
    get '/index', to: 'static_todos#index'
  
    resources :todos
  
  #resources :todos

  #get '/spaghettisause', to: 'todos#index'

  #root 'todos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    
      if @Todo.update(todo_params)
        redirect_to todos_path
      else
        render :edit
      end
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    
       if @todo.save
         redirect_to todos_path
       else
         render :new
       end
     end
    
     private
    
       def pages_params
         params.require(:page).permit(:title, :author, :body)
  end

  def destroy
    Todo.find(params[:id]).destroy
    redirect_to todos_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/create.html.erb
<h1>Todos#create</h1>
<p>Find me in app/views/todos/create.html.erb</p>

app/views/todos/destroy.html.erb
<h1>Todos#destroy</h1>
<p>Find me in app/views/todos/destroy.html.erb</p>

app/views/todos/edit.html.erb
<h1>Edit Page</h1>
<%= form_for @Todo do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :date %>
  <%= f.text_field :date %>

  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.submit %>
<% end %>

app/views/todos/index.html.erb
<h1>Your todo list</h1>
<% if @todos.empty? %>
    <h1> Nice you have nothing to do </h1>
<% else %>
    
    <% @todos.each do |todo| %>
        <li>
        <% todo.name %>
        </li>
<% end %>
<%= link_to 'Show Todo', todo_path(todo) %>
<%= link_to 'Add', new_todo_path %>
<%= link_to 'Edit Todo', edit_todo_path(todo) %>
<%= link_to 'Destroy Todo', todo, method: :delete %>
<p>Find me in app/views/todos/index.html.erb</p>

app/views/todos/new.html.erb
<h1>New Page</h1>
<%= form_for @Todo do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :date %>
  <%= f.text_field :date %>

  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.submit %>
<% end %>

app/views/todos/show.html.erb
<h1><%= @todo.name %></h1>
<h1><%= @todo.content %></h1>
<h1><%= @todo.date %></h1>
<%= link_to 'Back', todo_path %>
<p>Find me in app/views/todos/show.html.erb</p>

app/views/todos/update.html.erb
<h1>Todos#update</h1>
<p>Find me in app/views/todos/update.html.erb</p>